name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build
      run: bazel build java/com/google/cloud/deploymentmanager/autogen/...
    - name: Test
      run: bazel test javatests/com/google/cloud/deploymentmanager/autogen/...

